export const titles: string[] = [
    "CEO",
    "Software Engineer",
    "Product Manager",
    "Data Scientist",
    "Designer",
    "Marketing Manager",
    "Sales Executive",
    "HR Specialist",
    "Operations Manager",
    "Finance Analyst",
    "Chief Technology Officer",
    "Chief Financial Officer",
    "Content Writer",
    "DevOps Engineer",
    "Quality Assurance Engineer",
    "Customer Support Specialist",
    "Business Analyst",
    "UX/UI Designer",
    "Chief Marketing Officer",
    "Mobile Developer",
    "Backend Developer",
    "Frontend Developer",
    "Full Stack Developer",
    "Technical Lead",
    "Project Manager",
    "IT Support Specialist",
    "Database Administrator",
    "Security Analyst",
    "Network Engineer",
    "Social Media Manager",
    "SEO Specialist",
    "Content Strategist",
    "Chief Operating Officer",
    "Copywriter",
    "Graphic Designer",
    "Legal Advisor",
    "Recruitment Specialist",
    "Product Designer",
    "Systems Administrator",
    "AI/ML Engineer",
    "Cybersecurity Specialist",
    "Cloud Architect",
    "Technical Support Engineer",
    "Supply Chain Manager",
    "Logistics Coordinator",
    "Sales Manager",
    "Public Relations Specialist",
    "Event Planner",
    "Training and Development Manager",
    "E-commerce Manager",
    "Chief Data Officer"
  ];
  